version: '3.8'

services:
  github-scraper:
    build: .
    container_name: github-scraper
    volumes:
      - ./src/data_stages:/app/data_stages
    working_dir: /app
    command: python src/main.py
    environment:
      - PYTHONUNBUFFERED=1